apiVersion: v1
kind: Pod
metadata:
  generateName: aaarg-pod-
  labels:
    app: aaarg-proj
  namespace: 2198998bproject
spec:
  serviceAccountName: containerroot
  containers:
    - name: aaarg-notebook-env
      terminationMessagePath: /dev/termination-log
      command:
        - jupyter
      securityContext:
        capabilities:
          drop:
            - MKNOD
      ports:
        - containerPort: 8888
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: nfs-access
          mountPath: /nfs/
      terminationMessagePolicy: File
      image: 'brodiecode/aaarg-notebook-env:latest'
      args:
        - notebook
        - '--no-browser'
        - '--ip=0.0.0.0'
        - '--allow-root'
        - '--NotebookApp.token='
        - '--notebook-dir="/nfs/"'
  serviceAccount: containerroot
  volumes:
    - name: nfs-access
      persistentVolumeClaim:
        claimName: 2198998bvol1claim
