# Generated by Django 3.1.4 on 2021-01-06 18:41

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('instance', models.IntegerField(primary_key=True, serialize=False)),
                ('temporal', models.IntegerField(blank=True, null=True)),
                ('start_exec', models.DateTimeField(blank=True, null=True)),
                ('end_exec', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NuggetInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete_summary', models.IntegerField(blank=True, null=True)),
                ('found', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nugget_instances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nuggets',
            fields=[
                ('nugget_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('nugget_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nuggets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, default=None, editable=True, null=True, populate_from='name')),
            ],
            options={
                'db_table': 'techniques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('end', models.IntegerField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('topic_type', models.CharField(blank=True, db_column='type', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceMeta',
            fields=[
                ('topic', models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='presentation.topics')),
                ('summary', models.TextField(blank=True, null=True)),
                ('streamids', models.TextField(blank=True, null=True)),
                ('epoch_start', models.IntegerField(blank=True, null=True)),
                ('epoch_end', models.IntegerField(blank=True, null=True)),
                ('importance_score', models.IntegerField(blank=True, null=True)),
                ('total_importance', models.IntegerField(blank=True, null=True)),
                ('r1_precision', models.FloatField(blank=True, null=True)),
                ('r1_recall', models.FloatField(blank=True, null=True)),
                ('r1_fmeasure', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instance_meta',
                'managed': False,
            },
        ),
    ]
