# Generated by Django 3.1.4 on 2021-01-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniques',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'managed': True},
        ),
    ]
