apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jupyterroute
  namespace: 2198998bproject
spec:
  path: /
  to:
    kind: Service
    name: jupyterservice
  port:
    targetPort: 8888


